### ISSUE TITLE
Build failure due to missing mapv4v6addr.h

### ISSUE THREAD

**Issue by elkrejzi** [thkukuk/libnss_nis#1]
Build errors with:

nis-hosts.c:39:10: fatal error: 'resolv/mapv4v6addr.h' file not found
#include <resolv/mapv4v6addr.h>
         ^~~~~~~~~~~~~~~~~~~~~~
This seems to be a private header, not installed by default in glibc.

**Comment by thkukuk** [comment]
Should be fixed in git now.
