### ISSUE TITLE
[QUESTION] Is this package required to mDNSResponder by Apple on a Linux system?

### ISSUE THREAD

**Issue by Ks89** [thkukuk/libnss_nis#5]
I'm using a Linux embedded device with Yocto and I added mdns directly from Apple sources.
It contains a patch http://cgit.openembedded.org/meta-openembedded/tree/meta-networking/recipes-protocols/mdns/files/0001-nss_mdns-Do-not-include-nss.h-when-libc-glibc.patch?h=master to bypass nss.

Is this package required to use mdns (fully implemented in a standard way to pass certification procedures) or is it optional?

thank you.

**Comment by thkukuk** [comment]
The patch does not bypass NSS, as nss_mdns is a NSS module, that wouldn't make any sense as the module would become useless.

Else NIS has nothing to do with mdns, but as I'm not the author of Apples mdns implementation, I cannot answer your question. You need to ask Apple.
